# Generated by Django 4.2.30 on 2026-07-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=44, unique=True)),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by_telegram_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TokenBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('logo_url', models.URLField(blank=True, max_length=512)),
                ('logo_hash', models.CharField(blank=True, max_length=64)),
                ('contract_address', models.CharField(max_length=44)),
                ('amount', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='tracker.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MatchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('name', 'Name'), ('symbol', 'Symbol'), ('logo', 'Logo'), ('name+symbol', 'Name + Symbol'), ('name+logo', 'Name + Logo'), ('symbol+logo', 'Symbol + Logo'), ('name+symbol+logo', 'Name + Symbol + Logo')], max_length=32)),
                ('name_score', models.FloatField(blank=True, null=True)),
                ('symbol_score', models.FloatField(blank=True, null=True)),
                ('logo_distance', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('matched_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_match', to='tracker.tokenbuy')),
                ('new_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_new', to='tracker.tokenbuy')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenbuy',
            index=models.Index(fields=['wallet', '-timestamp'], name='tracker_tok_wallet__d4dbde_idx'),
        ),
    ]
