# Generated by Django 4.2.30 on 2026-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbuy',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tokenbuy',
            name='spent_symbol',
            field=models.CharField(default='SOL', max_length=16),
        ),
        migrations.AddField(
            model_name='tokenbuy',
            name='tx_signature',
            field=models.CharField(blank=True, db_index=True, max_length=88, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_anomaly_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
