# Generated by Django 4.2.30 on 2026-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tokenbuy_amount_spent_tokenbuy_spent_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenbuy',
            name='tx_signature',
            field=models.CharField(blank=True, db_index=True, max_length=88, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tokenbuy',
            unique_together={('wallet', 'tx_signature')},
        ),
    ]
