# Generated by Django 4.2.30 on 2026-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tokenbuy_tx_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbuy',
            name='creator',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
