# Generated by Django 4.2.30 on 2026-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tokenbuy_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenbuy',
            name='raw_payload',
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['new_buy', 'matched_buy'], name='tracker_mat_new_buy_e23aad_idx'),
        ),
    ]
